### PR TITLE
Feature/use node package

### PR DESCRIPTION
**Pull request by 5290charlie**

### CODE REVIEW

**Comment by 5290charlie** [comment]
@brandoncabael I have removed all the JavaScript logic from the repository, and rebuilt it as a standalone module & executable in https://github.com/cmr1/node-ts3-bot-verify-gw2

Now this `Dockerfile` can just run:
- `npm install --global cmr1-ts3-bot-verify-gw2`
- `ts3-bot-verify-gw2`

And that's literally all it does :)

Check it out, and approve the changes when you can (I want to simulate the integration process)

**Comment by brandoncabael** [comment]
Any chance you can add documentation to the readme before I approve?

**Review by brandoncabael — CHANGES_REQUESTED** [review]
I would say documentation just on the actual process to implement and setup is needed.

**Comment by 5290charlie** [comment]
@brandoncabael README has documentation on usage already, only assumption is that Docker is setup.

What were you looking for?

**Review by brandoncabael — APPROVED** [review]
Didn't show up on my phone which is weird... But it seems all checks have passed, and it looks great.

**Comment by 5290charlie** [comment]
@brandoncabael added you as collaborator with write access, apparently the review must be approved by someone with write access...

Might work automatically, otherwise try again

**Comment by 5290charlie** [comment]
WOOT! There it goes!

**Comment by brandoncabael** [comment]
Looks good!

**Pull request merged**
